// src/pages/Index.tsx

import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Lightbulb, Brain, Compass, Heart } from "lucide-react";

const Index = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      
      <main className="flex-grow">
        {/* Hero Section */}
        <section className="bg-gradient-to-b from-mind-purple-light to-white py-16 md:py-24">
          <div className="container mx-auto px-4">
            <div className="max-w-3xl mx-auto text-center">
              <h1 className="text-4xl md:text-5xl font-bold text-mind-purple-dark mb-4">
                Understand Your Mind, Navigate Your Life
              </h1>
              <p className="text-xl text-mind-gray-dark mb-8 leading-relaxed">
                Discover cognitive patterns, manage anxiety, explore career paths, and improve 
                your mental wellbeing through evidence-based tools and insights.
              </p>
              
              <div className="disclaimer max-w-2xl mx-auto mb-8">
                <strong>Important:</strong> MindNavigator is a self-help tool, not therapy or diagnosis. 
                If you're experiencing a crisis, please seek professional help immediately.
                <Link to="/resources/crisis" className="underline ml-1 text-mind-purple-dark">
                  Access crisis resources here.
                </Link>
              </div>
              
              <Link to="/signup">
                <Button className="bg-mind-purple-dark hover:bg-mind-purple-dark/90 text-white px-8 py-6 text-lg">
                  Get Started
                </Button>
              </Link>
            </div>
          </div>
        </section>
        
        {/* Features Section */}
        <section className="py-16">
          <div className="container mx-auto px-4">
            <h2 className="text-3xl font-bold text-center mb-12 text-mind-gray-dark">
              Discover a Better Understanding of Yourself
            </h2>
            
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
              <Card className="card-hover">
                <CardContent className="pt-6">
                  <div className="mb-4 bg-mind-blue-light p-3 rounded-full w-12 h-12 flex items-center justify-center">
                    <Brain className="text-mind-blue-dark" size={24} />
                  </div>
                  <h3 className="text-xl font-semibold mb-2">Identify Biases</h3>
                  <p className="text-mind-gray">
                    Recognize cognitive biases that affect your decisions and learn strategies to overcome them.
                  </p>
                </CardContent>
              </Card>
              
              <Card className="card-hover">
                <CardContent className="pt-6">
                  <div className="mb-4 bg-mind-purple-light p-3 rounded-full w-12 h-12 flex items-center justify-center">
                    <Lightbulb className="text-mind-purple-dark" size={24} />
                  </div>
                  <h3 className="text-xl font-semibold mb-2">Manage Anxiety</h3>
                  <p className="text-mind-gray">
                    Learn evidence-based techniques to understand and manage feelings of anxiety and stress.
                  </p>
                </CardContent>
              </Card>
              
              <Card className="card-hover">
                <CardContent className="pt-6">
                  <div className="mb-4 bg-mind-blue-light p-3 rounded-full w-12 h-12 flex items-center justify-center">
                    <Compass className="text-mind-blue-dark" size={24} />
                  </div>
                  <h3 className="text-xl font-semibold mb-2">Explore Career Paths</h3>
                  <p className="text-mind-gray">
                    Clarify your values and strengths to make more informed career and life decisions.
                  </p>
                </CardContent>
              </Card>
              
              <Card className="card-hover">
                <CardContent className="pt-6">
                  <div className="mb-4 bg-mind-purple-light p-3 rounded-full w-12 h-12 flex items-center justify-center">
                    <Heart className="text-mind-purple-dark" size={24} />
                  </div>
                  <h3 className="text-xl font-semibold mb-2">Build Self-Compassion</h3>
                  <p className="text-mind-gray">
                    Develop a kinder relationship with yourself through guided exercises and reflections.
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        
        {/* How It Works Section */}
        <section className="py-16 bg-mind-gray-light">
          <div className="container mx-auto px-4">
            <h2 className="text-3xl font-bold text-center mb-12 text-mind-gray-dark">
              How It Works
            </h2>
            
            <div className="max-w-4xl mx-auto">
              <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
                <div className="text-center">
                  <div className="bg-white rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4 shadow-sm border">
                    <span className="text-2xl font-bold text-mind-purple-dark">1</span>
                  </div>
                  <h3 className="font-semibold mb-2">Assess</h3>
                  <p className="text-sm text-mind-gray">Complete assessments to understand your patterns</p>
                </div>
                
                <div className="text-center">
                  <div className="bg-white rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4 shadow-sm border">
                    <span className="text-2xl font-bold text-mind-purple-dark">2</span>
                  </div>
                  <h3 className="font-semibold mb-2">Reflect</h3>
                  <p className="text-sm text-mind-gray">Journal and engage with interactive tools</p>
                </div>
                
                <div className="text-center">
                  <div className="bg-white rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4 shadow-sm border">
                    <span className="text-2xl font-bold text-mind-purple-dark">3</span>
                  </div>
                  <h3 className="font-semibold mb-2">Learn</h3>
                  <p className="text-sm text-mind-gray">Explore modules with evidence-based content</p>
                </div>
                
                <div className="text-center">
                  <div className="bg-white rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4 shadow-sm border">
                    <span className="text-2xl font-bold text-mind-purple-dark">4</span>
                  </div>
                  <h3 className="font-semibold mb-2">Grow</h3>
                  <p className="text-sm text-mind-gray">Track insights and progress over time</p>
                </div>
              </div>
              
              <div className="text-center mt-12">
                <Link to="/signup">
                  <Button className="bg-mind-purple-dark hover:bg-mind-purple-dark/90 text-white">
                    Start Your Journey
                  </Button>
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>
      
      <Footer />
    </div>
  );
};

export default Index;

// archive/Veramind-main/Veramind-main/src/pages/index.vue
<template>
  <div class="landing-page">
    <header class="landing-header">
      <nav class="landing-nav">
        <div class="nav-brand">
          <h1>VeraMind</h1>
        </div>
        <div class="nav-links">
          <RouterLink to="/login" class="btn btn-outline">Sign In</RouterLink>
          <RouterLink to="/signup" class="btn btn-primary">Get Started</RouterLink>
        </div>
      </nav>
    </header>

    <main class="landing-main">
      <section class="hero">
        <h1 class="hero-title">AI-Powered Mental Wellness</h1>
        <p class="hero-subtitle">
          Discover your cognitive patterns, manage anxiety, and grow with personalized insights
        </p>
        <div class="hero-actions">
          <RouterLink to="/signup" class="btn btn-primary btn-lg">Start Your Journey</RouterLink>
          <RouterLink to="/about" class="btn btn-outline btn-lg">Learn More</RouterLink>
        </div>
        <div class="hero-disclaimer">
          <p>⚠️ VeraMind is not a replacement for professional therapy. Seek immediate help in crisis situations.</p>
        </div>
      </section>

      <section class="features">
        <h2>Key Features</h2>
        <div class="features-grid">
          <div class="feature-card">
            <div class="feature-icon">📊</div>
            <h3>Assessments</h3>
            <p>Evidence-based mental health screenings and cognitive assessments</p>
          </div>
          <div class="feature-card">
            <div class="feature-icon">📔</div>
            <h3>Journaling</h3>
            <p>AI-powered journal insights to understand your patterns</p>
          </div>
          <div class="feature-card">
            <div class="feature-icon">📚</div>
            <h3>Learning Modules</h3>
            <p>Structured courses on anxiety management and cognitive awareness</p>
          </div>
          <div class="feature-card">
            <div class="feature-icon">💡</div>
            <h3>AI Insights</h3>
            <p>Personalized recommendations based on your data</p>
          </div>
        </div>
      </section>
    </main>

    <footer class="landing-footer">
      <p>&copy; {{ currentYear }} VeraMind. All rights reserved.</p>
      <div class="footer-links">
        <RouterLink to="/crisis">Crisis Support</RouterLink>
        <RouterLink to="/terms">Terms</RouterLink>
        <RouterLink to="/privacy">Privacy</RouterLink>
      </div>
    </footer>
  </div>
</template>

<script setup>
const currentYear = new Date().getFullYear()
</script>

<style scoped>
.landing-page {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

.landing-header {
  background-color: white;
  border-bottom: 1px solid var(--mind-gray-border);
  padding: var(--spacing-4) var(--spacing-6);
}

.landing-nav {
  max-width: 1200px;
  margin: 0 auto;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.nav-brand h1 {
  color: var(--mind-purple);
  margin: 0;
  font-size: var(--text-2xl);
}

.nav-links {
  display: flex;
  gap: var(--spacing-3);
}

.landing-main {
  flex: 1;
}

.hero {
  max-width: 800px;
  margin: 0 auto;
  padding: var(--spacing-16) var(--spacing-6);
  text-align: center;
}

.hero-title {
  font-size: var(--text-5xl);
  margin-bottom: var(--spacing-6);
  color: var(--mind-gray-dark);
}

.hero-subtitle {
  font-size: var(--text-xl);
  color: var(--mind-gray);
  margin-bottom: var(--spacing-8);
  line-height: 1.6;
}

.hero-actions {
  display: flex;
  gap: var(--spacing-4);
  justify-content: center;
  margin-bottom: var(--spacing-8);
}

.hero-disclaimer {
  padding: var(--spacing-4);
  background-color: var(--mind-blue-light);
  border-left: 4px solid var(--warning);
  border-radius: var(--radius-md);
  max-width: 600px;
  margin: 0 auto;
}

.hero-disclaimer p {
  margin: 0;
  font-size: var(--text-sm);
  color: var(--mind-gray-dark);
}

.features {
  max-width: 1200px;
  margin: 0 auto;
  padding: var(--spacing-16) var(--spacing-6);
}

.features h2 {
  text-align: center;
  margin-bottom: var(--spacing-12);
}

.features-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: var(--spacing-6);
}

.feature-card {
  background-color: white;
  padding: var(--spacing-6);
  border-radius: var(--radius-lg);
  border: 1px solid var(--mind-gray-border);
  text-align: center;
  transition: all var(--transition-base);
}

.feature-card:hover {
  box-shadow: var(--shadow-lg);
  transform: translateY(-4px);
}

.feature-icon {
  font-size: 3rem;
  margin-bottom: var(--spacing-4);
}

.feature-card h3 {
  margin-bottom: var(--spacing-3);
}

.feature-card p {
  color: var(--mind-gray);
  margin: 0;
}

.landing-footer {
  background-color: white;
  border-top: 1px solid var(--mind-gray-border);
  padding: var(--spacing-6);
  text-align: center;
}

.footer-links {
  display: flex;
  gap: var(--spacing-4);
  justify-content: center;
  margin-top: var(--spacing-4);
}

.footer-links a {
  color: var(--mind-gray);
  font-size: var(--text-sm);
}
</style>
