// src/pages/SignUp.tsx

import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardFooter, CardHeader } from "@/components/ui/card";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { useAuth } from "@/contexts/AuthContext";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";

const signupSchema = z.object({
  name: z.string().min(1, "Name is required"),
  email: z.string().email("Please enter a valid email address"),
  password: z.string().min(6, "Password must be at least 6 characters long"),
});

type SignupFormValues = z.infer<typeof signupSchema>;

const SignUp = () => {
  const { signUp, isLoading } = useAuth();
  const form = useForm<SignupFormValues>({
    resolver: zodResolver(signupSchema),
    defaultValues: {
      name: "",
      email: "",
      password: "",
    },
  });

  const onSubmit = async (values: SignupFormValues) => {
    await signUp(values.email, values.password, values.name);
  };

  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      
      <div className="flex-grow flex items-center justify-center bg-mind-gray-light p-4">
        <div className="w-full max-w-md">
          <Card className="shadow-lg">
            <CardHeader>
              <h1 className="text-2xl font-bold text-center text-mind-purple-dark">Create your account</h1>
              <p className="text-mind-gray text-center mt-2">
                Join MindNavigator to start your self-improvement journey
              </p>
            </CardHeader>
            
            <CardContent>
              <Form {...form}>
                <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
                  <FormField
                    control={form.control}
                    name="name"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Full Name</FormLabel>
                        <FormControl>
                          <Input 
                            placeholder="Enter your name" 
                            {...field} 
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  
                  <FormField
                    control={form.control}
                    name="email"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Email</FormLabel>
                        <FormControl>
                          <Input 
                            type="email"
                            placeholder="Enter your email" 
                            {...field} 
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  
                  <FormField
                    control={form.control}
                    name="password"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Password</FormLabel>
                        <FormControl>
                          <Input 
                            type="password" 
                            placeholder="Create a password" 
                            {...field} 
                          />
                        </FormControl>
                        <p className="text-xs text-mind-gray mt-1">
                          Must be at least 6 characters long
                        </p>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  
                  <div className="mt-2">
                    <Button 
                      type="submit" 
                      className="w-full bg-mind-purple-dark hover:bg-mind-purple-dark/90"
                      disabled={isLoading}
                    >
                      {isLoading ? "Signing Up..." : "Sign Up"}
                    </Button>
                  </div>
                </form>
              </Form>
              
              <div className="mt-6 text-center">
                <p className="text-sm text-mind-gray">
                  By signing up, you agree to our{" "}
                  <Link to="/terms" className="text-mind-purple-dark hover:underline">
                    Terms of Service
                  </Link>{" "}
                  and{" "}
                  <Link to="/privacy" className="text-mind-purple-dark hover:underline">
                    Privacy Policy
                  </Link>
                  .
                </p>
              </div>
            </CardContent>
            
            <CardFooter className="flex justify-center border-t bg-mind-gray-light/50">
              <p className="text-sm text-mind-gray">
                Already have an account?{" "}
                <Link to="/login" className="text-mind-purple-dark hover:underline">
                  Log in
                </Link>
              </p>
            </CardFooter>
          </Card>
          
          <div className="disclaimer mt-6 text-center">
            <strong>Note:</strong> MindNavigator is not a substitute for professional mental health treatment.
          </div>
        </div>
      </div>
      
      <Footer />
    </div>
  );
};

export default SignUp;

// archive/Veramind-main/Veramind-main/src/pages/signup.vue
<template>
  <div class="auth-page">
    <div class="auth-container">
      <div class="auth-card">
        <h1>Create Account</h1>
        <p class="auth-subtitle">Start your mental wellness journey</p>

        <form @submit.prevent="handleSignup" class="auth-form">
          <div class="form-group">
            <label class="form-label">Full Name</label>
            <input
              v-model="fullName"
              type="text"
              class="form-input"
              :class="{ error: errors.fullName }"
              placeholder="John Doe"
              required
            />
            <span v-if="errors.fullName" class="form-error">{{ errors.fullName }}</span>
          </div>

          <div class="form-group">
            <label class="form-label">Email</label>
            <input
              v-model="email"
              type="email"
              class="form-input"
              :class="{ error: errors.email }"
              placeholder="your@email.com"
              required
            />
            <span v-if="errors.email" class="form-error">{{ errors.email }}</span>
          </div>

          <div class="form-group">
            <label class="form-label">Password</label>
            <input
              v-model="password"
              type="password"
              class="form-input"
              :class="{ error: errors.password }"
              placeholder="••••••••"
              required
              minlength="8"
            />
            <span v-if="errors.password" class="form-error">{{ errors.password }}</span>
            <small class="form-hint">At least 8 characters</small>
          </div>

          <div class="form-group">
            <label class="form-label">Confirm Password</label>
            <input
              v-model="confirmPassword"
              type="password"
              class="form-input"
              :class="{ error: errors.confirmPassword }"
              placeholder="••••••••"
              required
            />
            <span v-if="errors.confirmPassword" class="form-error">{{ errors.confirmPassword }}</span>
          </div>

          <div class="form-group">
            <label class="form-checkbox">
              <input type="checkbox" v-model="acceptTerms" required />
              <span>I agree to the <RouterLink to="/terms" target="_blank">Terms of Service</RouterLink> and <RouterLink to="/privacy" target="_blank">Privacy Policy</RouterLink></span>
            </label>
          </div>

          <button 
            type="submit" 
            class="btn btn-primary btn-lg"
            :disabled="loading || !acceptTerms"
          >
            <span v-if="loading" class="loading"></span>
            <span v-else>Create Account</span>
          </button>
        </form>

        <div class="auth-links">
          <p>Already have an account? <RouterLink to="/login">Sign in</RouterLink></p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useAuth } from '../composables/useAuth'
import { useToast } from '../composables/useToast'
import { useRouter } from 'vue-router'
import { isValidEmail } from '../utils/utils'

const { signUp } = useAuth()
const { success, error: showError } = useToast()
const router = useRouter()

const fullName = ref('')
const email = ref('')
const password = ref('')
const confirmPassword = ref('')
const acceptTerms = ref(false)
const loading = ref(false)
const errors = ref({})

const handleSignup = async () => {
  errors.value = {}

  // Validation
  if (!fullName.value.trim()) {
    errors.value.fullName = 'Full name is required'
  }

  if (!isValidEmail(email.value)) {
    errors.value.email = 'Please enter a valid email'
  }

  if (password.value.length < 8) {
    errors.value.password = 'Password must be at least 8 characters'
  }

  if (password.value !== confirmPassword.value) {
    errors.value.confirmPassword = 'Passwords do not match'
  }

  if (Object.keys(errors.value).length > 0) {
    return
  }

  loading.value = true

  try {
    const { data, error } = await signUp(email.value, password.value, fullName.value)

    if (error) {
      errors.value.general = error.message
      showError(error.message)
      return
    }

    success('Account created successfully!')
    await router.push('/dashboard')
  } catch (err) {
    showError('An unexpected error occurred')
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.auth-page {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, var(--mind-purple-light) 0%, var(--mind-blue-light) 100%);
  padding: var(--spacing-6);
}

.auth-container {
  width: 100%;
  max-width: 400px;
}

.auth-card {
  background-color: white;
  padding: var(--spacing-8);
  border-radius: var(--radius-xl);
  box-shadow: var(--shadow-xl);
}

.auth-card h1 {
  text-align: center;
  margin-bottom: var(--spacing-2);
}

.auth-subtitle {
  text-align: center;
  color: var(--mind-gray);
  margin-bottom: var(--spacing-8);
}

.auth-form {
  margin-bottom: var(--spacing-6);
}

.form-hint {
  display: block;
  font-size: var(--text-xs);
  color: var(--mind-gray);
  margin-top: var(--spacing-1);
}

.form-checkbox {
  display: flex;
  align-items: flex-start;
  gap: var(--spacing-2);
  cursor: pointer;
  font-size: var(--text-sm);
}

.form-checkbox input[type="checkbox"] {
  width: auto;
  margin-top: 2px;
  cursor: pointer;
}

.form-checkbox a {
  color: var(--mind-purple);
  text-decoration: underline;
}

.auth-links {
  text-align: center;
  font-size: var(--text-sm);
}

.auth-links a {
  color: var(--mind-purple);
}

.auth-links p {
  color: var(--mind-gray);
}
</style>
