// archive/src/components/Footer.tsx

import { Link } from "react-router-dom";

const Footer = () => {
  return (
    <footer className="bg-white border-t">
      <div className="container mx-auto px-4 py-6">
        <div className="flex flex-col md:flex-row justify-between">
          <div className="mb-6 md:mb-0">
            <h3 className="text-lg font-semibold text-mind-purple-dark">MindNavigator</h3>
            <p className="text-sm text-mind-gray mt-2 max-w-md">
              A self-help tool designed to help identify cognitive biases, manage anxiety, and improve mental wellbeing.
            </p>
          </div>
          
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-8">
            <div>
              <h4 className="font-medium text-mind-gray-dark mb-4">Resources</h4>
              <ul className="space-y-2 text-sm">
                <li>
                  <Link to="/resources" className="text-mind-gray hover:text-mind-purple-dark">
                    Mental Health Resources
                  </Link>
                </li>
                <li>
                  <Link to="/resources/crisis" className="text-destructive font-medium">
                    Crisis Support
                  </Link>
                </li>
              </ul>
            </div>
            
            <div>
              <h4 className="font-medium text-mind-gray-dark mb-4">Company</h4>
              <ul className="space-y-2 text-sm">
                <li>
                  <Link to="/about" className="text-mind-gray hover:text-mind-purple-dark">
                    About Us
                  </Link>
                </li>
                <li>
                  <Link to="/contact" className="text-mind-gray hover:text-mind-purple-dark">
                    Contact
                  </Link>
                </li>
              </ul>
            </div>
            
            <div>
              <h4 className="font-medium text-mind-gray-dark mb-4">Legal</h4>
              <ul className="space-y-2 text-sm">
                <li>
                  <Link to="/terms" className="text-mind-gray hover:text-mind-purple-dark">
                    Terms of Use
                  </Link>
                </li>
                <li>
                  <Link to="/privacy" className="text-mind-gray hover:text-mind-purple-dark">
                    Privacy Policy
                  </Link>
                </li>
                <li>
                  <Link to="/disclaimer" className="text-mind-gray hover:text-mind-purple-dark">
                    Disclaimer
                  </Link>
                </li>
              </ul>
            </div>
          </div>
        </div>
        
        <div className="crisis-support mt-6 text-center">
          <strong>Need immediate help?</strong> If you're in crisis, please call the National Suicide Prevention Lifeline at <a href="tel:988" className="underline font-bold">988</a> or text HOME to 741741
        </div>
        
        <div className="border-t mt-6 pt-6 text-center text-sm text-mind-gray">
          © {new Date().getFullYear()} MindNavigator. All rights reserved.
        </div>
      </div>
    </footer>
  );
};

export default Footer;

// archive/Veramind-main/Veramind-main/src/components/Footer.vue
<template>
  <footer class="footer">
    <div class="footer-content">
      <div class="footer-section">
        <h4>VeraMind</h4>
        <p class="footer-disclaimer">
          VeraMind is not a replacement for professional therapy or medical treatment.
          If you're experiencing a crisis, please seek immediate help.
        </p>
      </div>
      <div class="footer-section">
        <h4>Resources</h4>
        <RouterLink to="/crisis" class="footer-link">Crisis Support</RouterLink>
        <RouterLink to="/resources" class="footer-link">Find Help</RouterLink>
        <RouterLink to="/educational-materials" class="footer-link">Educational Materials</RouterLink>
      </div>
      <div class="footer-section">
        <h4>Legal</h4>
        <RouterLink to="/terms" class="footer-link">Terms of Service</RouterLink>
        <RouterLink to="/privacy" class="footer-link">Privacy Policy</RouterLink>
      </div>
    </div>
    <div class="footer-bottom">
      <p>&copy; {{ currentYear }} VeraMind. All rights reserved.</p>
    </div>
  </footer>
</template>

<script setup>
const currentYear = new Date().getFullYear()
</script>

<style scoped>
.footer {
  background-color: white;
  border-top: 1px solid var(--mind-gray-border);
  padding: var(--spacing-8) var(--spacing-6);
  margin-top: auto;
}

.footer-content {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: var(--spacing-8);
  margin-bottom: var(--spacing-6);
}

.footer-section h4 {
  font-size: var(--text-lg);
  font-weight: var(--font-semibold);
  margin-bottom: var(--spacing-4);
  color: var(--mind-gray-dark);
}

.footer-disclaimer {
  font-size: var(--text-sm);
  color: var(--mind-gray);
  line-height: 1.6;
}

.footer-link {
  display: block;
  color: var(--mind-gray);
  margin-bottom: var(--spacing-2);
  font-size: var(--text-sm);
  transition: color var(--transition-fast);
}

.footer-link:hover {
  color: var(--mind-purple);
}

.footer-bottom {
  text-align: center;
  padding-top: var(--spacing-6);
  border-top: 1px solid var(--mind-gray-border);
  color: var(--mind-gray);
  font-size: var(--text-sm);
}
</style>
